"""축구 선수 초성퀴즈용 선수 DB (수작업 100명).

- PLAYER_DB에 100명의 메이저(현역/은퇴) 선수 정보를 담았습니다.
- app.py의 /kakao/playerquiz에서 사용합니다.

필드(권장)
- id, name_ko, aliases, img_url, birth_year, nationality, position, one_liner
- chosung은 비워도 됩니다(없으면 app.py에서 자동 생성).
"""

from __future__ import annotations
from typing import Dict, List

_CHOSUNG_LIST = [
    "ㄱ", "ㄲ", "ㄴ", "ㄷ", "ㄸ", "ㄹ", "ㅁ", "ㅂ", "ㅃ", "ㅅ",
    "ㅆ", "ㅇ", "ㅈ", "ㅉ", "ㅊ", "ㅋ", "ㅌ", "ㅍ", "ㅎ",
]


def make_chosung(text: str) -> str:
    """한글 문자열에서 초성만 추출. 공백/영문/숫자는 그대로 둠."""
    out: List[str] = []
    for ch in text:
        code = ord(ch)
        if 0xAC00 <= code <= 0xD7A3:
            idx = (code - 0xAC00) // 588
            out.append(_CHOSUNG_LIST[idx])
        else:
            out.append(ch)
    return "".join(out)


PLAYER_DB: List[Dict] = [
    # ====== GOAT / 레전드급 ======
    {
        "id": "lionel_messi",
        "name_ko": "리오넬 메시",
        "aliases": ["메시", "Messi", "라풀가", "LaPulga"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852158023.png?rd=202601271040",
        "chosung": "",
        "birth_year": 1987,
        "nationality": "아르헨티나",
        "position": "FW",
        "one_liner": "바르셀로나의 상징으로 불린 왼발 드리블러, ‘메시존’과 플레이메이킹이 트레이드마크",
    },
    {
        "id": "cristiano_ronaldo",
        "name_ko": "크리스티아누 호날두",
        "aliases": ["호날두", "CR7", "Ronaldo", "크리스티아노 호날두"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p855020801.png?rd=202601271040",
        "chosung": "",
        "birth_year": 1985,
        "nationality": "포르투갈",
        "position": "FW",
        "one_liner": "‘CR7’로 불리는 포르투갈 레전드 공격수, 공중전·피지컬·득점력으로 상징",
    },
    {
        "id": "pele",
        "name_ko": "펠레",
        "aliases": ["펠레", "Pele", "Pelé", "오레이"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p100190043.png?rd=202601271040",
        "chosung": "",
        "birth_year": 1940,
        "nationality": "브라질",
        "position": "FW",
        "one_liner": "브라질 축구의 상징으로 불린 전설, 월드컵 우승과 ‘축구의 왕’ 이미지로 유명",
    },
    {
        "id": "diego_maradona",
        "name_ko": "디에고 마라도나",
        "aliases": ["마라도나", "Maradona", "디에구 마라도나"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852190042.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1960,
        "nationality": "아르헨티나",
        "position": "MF",
        "one_liner": "‘신의 손’과 폭발적 드리블로 회자되는 아르헨티나 레전드, 나폴리 영웅 서사",
    },
    {
        "id": "zinedine_zidane",
        "name_ko": "지네딘 지단",
        "aliases": ["지단", "Zidane", "Zizou"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p829001397.png?rd=202601271040",
        "chosung": "",
        "birth_year": 1972,
        "nationality": "프랑스",
        "position": "MF",
        "one_liner": "우아한 터치·탈압박의 상징, 프랑스 월드컵 우승과 레알 ‘지단 발리’로 유명",
    },
    {
        "id": "johan_cruyff",
        "name_ko": "요한 크루이프",
        "aliases": ["크루이프", "Cruyff", "크루이프턴"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p825190045.png?rd=202601271040",
        "chosung": "",
        "birth_year": 1947,
        "nationality": "네덜란드",
        "position": "FW",
        "one_liner": "‘토탈 풋볼’의 아이콘, 크루이프 턴으로도 유명한 네덜란드/바르사 레전드",
    },
    {
        "id": "franz_beckenbauer",
        "name_ko": "프란츠 베켄바워",
        "aliases": ["베켄바워", "Beckenbauer", "프란츠 배켄바워"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p836168473.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1945,
        "nationality": "독일",
        "position": "DF",
        "one_liner": "‘카이저’ 별명, 리베로의 대명사로 불린 독일 레전드 수비수",
    },
    {
        "id": "ronaldo_nazario",
        "name_ko": "호나우두",
        "aliases": ["호나우두", "Ronaldo", "R9", "현역아님호날두"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p850037576.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1976,
        "nationality": "브라질",
        "position": "FW",
        "one_liner": "‘R9’로 불린 브라질 괴물 스트라이커, 폭발적 스피드·드리블·골결정력의 상징",
    },
    {
        "id": "ronaldinho",
        "name_ko": "호나우지뉴",
        "aliases": ["호나우지뉴", "Ronaldinho", "딩요"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p827028130.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1980,
        "nationality": "브라질",
        "position": "FW",
        "one_liner": "웃으며 축구하는 이미지의 대표, 바르사 시절 화려한 개인기·패스로 팬을 사로잡음",
    },
    {
        "id": "kaka",
        "name_ko": "카카",
        "aliases": ["카카", "Kaka", "Kaká"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p850138449.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1982,
        "nationality": "브라질",
        "position": "MF",
        "one_liner": "밀란 전성기의 상징, 폭발적 드리블 돌파와 중거리로 ‘발롱도르’ 커리어를 남김",
    },

    # ====== 현역 메가스타 / 공격수 ======
    {
        "id": "kylian_mbappe",
        "name_ko": "킬리안 음바페",
        "aliases": ["음바페", "Mbappe", "Mbappé"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p231747_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1998,
        "nationality": "프랑스",
        "position": "FW",
        "one_liner": "폭발적 스피드로 뒷공간을 찢는 프랑스 에이스, 월드컵에서 ‘결정력’ 이미지 확립",
    },
    {
        "id": "erling_haaland",
        "name_ko": "엘링 홀란",
        "aliases": ["홀란", "홀란드", "Haaland", "엘린 홀란"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p844239085_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 2000,
        "nationality": "노르웨이",
        "position": "FW",
        "one_liner": "박스 안 움직임과 피지컬로 골을 쓸어 담는 스트라이커, ‘득점 기계’ 이미지",
    },
    {
        "id": "neymar",
        "name_ko": "네이마르",
        "aliases": ["네이마르 주니오르", "네이마르 Jr", "Neymar", "네이마루"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/players/p190871.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1992,
        "nationality": "브라질",
        "position": "FW",
        "one_liner": "산투스·바르사·PSG를 거친 브라질 스타, 화려한 개인기와 기술 축구의 상징",
    },
    {
        "id": "mohamed_salah",
        "name_ko": "모하메드 살라",
        "aliases": ["살라", "Salah", "이집트왕", "모하메두 살라"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p831209331_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1992,
        "nationality": "이집트",
        "position": "FW",
        "one_liner": "‘이집트의 왕’ 별명, 왼발 컷인·골결정력으로 리버풀 공격을 대표",
    },
    {
        "id": "harry_kane",
        "name_ko": "해리 케인",
        "aliases": ["케인", "Kane", "헤리 케인", "해리 캐인"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p202126_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1993,
        "nationality": "잉글랜드",
        "position": "FW",
        "one_liner": "득점과 연계를 동시에 하는 정통 9번, 내려와서 패스 뿌리는 ‘플레이메이커형 스트라이커’",
    },
    {
        "id": "karim_benzema",
        "name_ko": "카림 벤제마",
        "aliases": ["벤제마", "Benzema"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848165153_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1987,
        "nationality": "프랑스",
        "position": "FW",
        "one_liner": "레알 마드리드 공격의 축, 연계·움직임·결정력으로 ‘완성형 9번’ 이미지",
    },
    {
        "id": "robert_lewandowski",
        "name_ko": "로베르트 레반도프스키",
        "aliases": ["레반도프스키", "레반", "Lewandowski", "로베르토 레반도프스키"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852188545.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1988,
        "nationality": "폴란드",
        "position": "FW",
        "one_liner": "바이에른·바르사에서 득점력을 뽐낸 골잡이, 박스 안 움직임과 마무리가 강점",
    },
    {
        "id": "luis_suarez",
        "name_ko": "루이스 수아레스",
        "aliases": ["수아레스", "Suarez", "엘피스톨레로"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848176580_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1987,
        "nationality": "우루과이",
        "position": "FW",
        "one_liner": "강한 집념과 박스 안 킬러 본능의 우루과이 스트라이커, 바르사 MSN 라인 기억",
    },
    {
        "id": "antoine_griezmann",
        "name_ko": "앙투안 그리즈만",
        "aliases": ["그리즈만", "Griezmann", "앙투앙 그리즈만"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p851194765.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1991,
        "nationality": "프랑스",
        "position": "FW",
        "one_liner": "활동량·연계·결정력을 겸비한 ‘만능 2선/세컨 스트라이커’, 프랑스 우승 멤버",
    },
    {
        "id": "sergio_aguero",
        "name_ko": "세르히오 아구에로",
        "aliases": ["아구에로", "Aguero", "Kun", "쿤"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/players/p153079.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1988,
        "nationality": "아르헨티나",
        "position": "FW",
        "one_liner": "맨시티 레전드 골잡이, ‘AGUEROOOO!’ 극장골로 상징되는 결정력의 아이콘",
    },
    {
        "id": "zlatan_ibrahimovic",
        "name_ko": "즐라탄 이브라히모비치",
        "aliases": ["즐라탄", "이브라히모비치", "Ibrahimovic", "Ibra"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p284041236.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1981,
        "nationality": "스웨덴",
        "position": "FW",
        "one_liner": "거대한 피지컬+기술을 겸비한 ‘카리스마 9번’, 오버헤드킥 같은 임팩트 장면 다수",
    },
    {
        "id": "thierry_henry",
        "name_ko": "티에리 앙리",
        "aliases": ["앙리", "Henry"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848001625.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1977,
        "nationality": "프랑스",
        "position": "FW",
        "one_liner": "아스날 ‘무적함대’의 상징, 빠른 침투와 왼발 마무리로 대표되는 프리미어리그 레전드",
    },
    {
        "id": "didier_drogba",
        "name_ko": "디디에 드로그바",
        "aliases": ["드로그바", "Drogba"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852031432.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1978,
        "nationality": "코트디부아르",
        "position": "FW",
        "one_liner": "첼시의 ‘결승전 사나이’로 불린 피지컬 스트라이커, 큰 경기에서 강한 이미지",
    },

    # ====== 미드필더 / 플레이메이커 ======
    {
        "id": "kevin_de_bruyne",
        "name_ko": "케빈 더브라위너",
        "aliases": ["더브라위너", "KDB", "De Bruyne", "DeBruyne", "케빈 데브라위너"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852192985.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1991,
        "nationality": "벨기에",
        "position": "MF",
        "one_liner": "‘KDB’로 불리는 킬패스 장인, 맨시티 공격 전개의 중심",
    },
    {
        "id": "luka_modric",
        "name_ko": "루카 모드리치",
        "aliases": ["모드리치", "Modric", "Modrić"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p177003_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1985,
        "nationality": "크로아티아",
        "position": "MF",
        "one_liner": "레알 중원의 상징, 탈압박·템포 조절·바깥 발 패스로 경기를 지배",
    },
    {
        "id": "toni_kroos",
        "name_ko": "토니 크로스",
        "aliases": ["크로스", "Kroos"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p807182521.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1990,
        "nationality": "독일",
        "position": "MF",
        "one_liner": "패스 정확도와 롱패스 전개로 유명한 ‘정확함의 화신’, 레알 빌드업의 핵",
    },
    {
        "id": "andres_iniesta",
        "name_ko": "안드레스 이니에스타",
        "aliases": ["이니에스타", "Iniesta"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848000041.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1984,
        "nationality": "스페인",
        "position": "MF",
        "one_liner": "좁은 공간 탈압박과 ‘라스트 패스’ 감각으로 상징되는 바르사/스페인 레전드",
    },
    {
        "id": "xavi",
        "name_ko": "사비 에르난데스",
        "aliases": ["사비", "Xavi"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p845010535.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1980,
        "nationality": "스페인",
        "position": "MF",
        "one_liner": "티키타카의 핵, 짧은 패스와 포지셔닝으로 경기를 설계한 바르사 전설",
    },
    {
        "id": "sergio_busquets",
        "name_ko": "세르히오 부스케츠",
        "aliases": ["부스케츠", "Busquets", "부시"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848189511_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1988,
        "nationality": "스페인",
        "position": "MF",
        "one_liner": "한 템포 느리게 빠져나오는 ‘탈압박/시야’가 상징, 바르사 수미의 교과서",
    },
    {
        "id": "ngolo_kante",
        "name_ko": "은골로 캉테",
        "aliases": ["캉테", "Kante", "Kanté"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p215914_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1991,
        "nationality": "프랑스",
        "position": "MF",
        "one_liner": "미친 활동량으로 중원을 쓸어 담는 볼위닝 미드필더, ‘작은 거인’ 이미지",
    },
    {
        "id": "paul_pogba",
        "name_ko": "폴 포그바",
        "aliases": ["포그바", "Pogba"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/players/p195864.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1993,
        "nationality": "프랑스",
        "position": "MF",
        "one_liner": "피지컬+기술을 겸비한 박투박 미드필더, 롱패스·중거리로 임팩트 장면이 많음",
    },
    {
        "id": "casemiro",
        "name_ko": "카세미루",
        "aliases": ["카세미루", "Casemiro"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p200145_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1992,
        "nationality": "브라질",
        "position": "MF",
        "one_liner": "거친 수비와 위치 선정으로 유명한 수비형 미드필더, 레알 ‘중원 삼각형’의 방패",
    },
    {
        "id": "bruno_fernandes",
        "name_ko": "브루노 페르난데스",
        "aliases": ["브루노", "Bruno", "Fernandes", "브루누 페르난데스"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852212198.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1994,
        "nationality": "포르투갈",
        "position": "MF",
        "one_liner": "중거리·킬패스·세트피스가 강한 공격형 미드필더, 맨유 전개의 중심 역할",
    },
    {
        "id": "bernardo_silva",
        "name_ko": "베르나르두 실바",
        "aliases": ["베실", "베르나르두", "Bernardo", "Bernardo Silva"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p218667_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1994,
        "nationality": "포르투갈",
        "position": "MF",
        "one_liner": "좁은 공간 볼키핑과 압박 회피가 강점, 맨시티의 ‘끈적한 드리블+연결’ 카드",
    },
    {
        "id": "rodri",
        "name_ko": "로드리",
        "aliases": ["로드리", "Rodri", "Rodrigo"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p231866_25.png?rd=202601271050",
        "chosung": "",
        "birth_year": 1996,
        "nationality": "스페인",
        "position": "MF",
        "one_liner": "수미 자리에서 빌드업과 수비 밸런스를 동시에 잡는 맨시티의 엔진",
    },
    {
        "id": "jude_bellingham",
        "name_ko": "주드 벨링엄",
        "aliases": ["벨링엄", "Bellingham"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p855252371.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2003,
        "nationality": "잉글랜드",
        "position": "MF",
        "one_liner": "박스 투 박스에서 득점까지 해내는 ‘올라운더’, 레알 이적 후 스타성 급상승",
    },
    {
        "id": "pedri",
        "name_ko": "페드리",
        "aliases": ["페드리", "Pedri"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852251854.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2002,
        "nationality": "스페인",
        "position": "MF",
        "one_liner": "패스 템포와 공간 인지가 뛰어난 바르사 미드필더, ‘차세대 이니에스타’로도 언급",
    },
    {
        "id": "gavi",
        "name_ko": "가비",
        "aliases": ["가비", "Gavi"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p264240_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2004,
        "nationality": "스페인",
        "position": "MF",
        "one_liner": "거침없는 압박과 투지로 유명한 바르사 미드필더, 경기장 ‘파이터’ 이미지",
    },
    {
        "id": "declan_rice",
        "name_ko": "데클란 라이스",
        "aliases": ["라이스", "Rice", "데클런 라이스"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p234378_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1999,
        "nationality": "잉글랜드",
        "position": "MF",
        "one_liner": "수비 커버 범위와 전진 드리블이 강한 수미/박투박, 잉글랜드 중원의 핵",
    },
    {
        "id": "christian_eriksen",
        "name_ko": "크리스티안 에릭센",
        "aliases": ["에릭센", "Eriksen"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p190460_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1992,
        "nationality": "덴마크",
        "position": "MF",
        "one_liner": "세트피스와 중거리, 침투 패스로 유명한 플레이메이커, 토트넘 시절 인상적",
    },
    {
        "id": "andrea_pirlo",
        "name_ko": "안드레아 피를로",
        "aliases": ["피를로", "Pirlo", "마에스트로"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p814007763.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1979,
        "nationality": "이탈리아",
        "position": "MF",
        "one_liner": "롱패스와 프리킥으로 경기를 지휘한 ‘마에스트로’, 뒤에서 조율하는 딥라잉 플레이메이커",
    },
    {
        "id": "francesco_totti",
        "name_ko": "프란체스코 토티",
        "aliases": ["토티", "Totti", "로마왕자"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848001238.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1976,
        "nationality": "이탈리아",
        "position": "FW",
        "one_liner": "로마 원클럽의 상징 ‘로마 왕자’, 중거리·킬패스로 팀을 이끈 캡틴",
    },

    # ====== 수비수 / 센터백 / 풀백 ======
    {
        "id": "virgil_van_dijk",
        "name_ko": "버질 반다이크",
        "aliases": ["반다이크", "Van Dijk", "VanDijk", "VVD"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p831203376_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1991,
        "nationality": "네덜란드",
        "position": "DF",
        "one_liner": "리버풀 수비를 재건한 센터백으로 평가, 공중볼·대인수비·리더십이 상징",
    },
    {
        "id": "sergio_ramos",
        "name_ko": "세르히오 라모스",
        "aliases": ["라모스", "Ramos"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/players/p155862.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1986,
        "nationality": "스페인",
        "position": "DF",
        "one_liner": "강한 투지와 ‘극장골’로도 유명한 레알 캡틴, 거친 수비와 리더십의 아이콘",
    },
    {
        "id": "gerard_pique",
        "name_ko": "제라르 피케",
        "aliases": ["피케", "Pique", "Piqué"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/players/p152729.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1987,
        "nationality": "스페인",
        "position": "DF",
        "one_liner": "바르사 빌드업 수비의 상징, 공을 다루는 센터백으로 유명",
    },
    {
        "id": "carles_puyol",
        "name_ko": "카를레스 푸욜",
        "aliases": ["푸욜", "Puyol", "캡틴"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p825013038.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1978,
        "nationality": "스페인",
        "position": "DF",
        "one_liner": "바르사의 투혼 캡틴, 몸 던지는 수비와 리더십으로 레전드 반열",
    },
    {
        "id": "paolo_maldini",
        "name_ko": "파올로 말디니",
        "aliases": ["말디니", "Maldini"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p836001109.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1968,
        "nationality": "이탈리아",
        "position": "DF",
        "one_liner": "밀란 수비의 대명사, 클래스와 위치 선정으로 ‘수비의 교과서’로 불림",
    },
    {
        "id": "fabio_cannavaro",
        "name_ko": "파비오 칸나바로",
        "aliases": ["칸나바로", "Cannavaro"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p289001183.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1973,
        "nationality": "이탈리아",
        "position": "DF",
        "one_liner": "2006 월드컵 우승을 이끈 센터백, 작은 체구로 공중볼까지 강한 수비수 이미지",
    },
    {
        "id": "giorgio_chiellini",
        "name_ko": "조르조 키엘리니",
        "aliases": ["키엘리니", "Chiellini"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848138956.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1984,
        "nationality": "이탈리아",
        "position": "DF",
        "one_liner": "유벤투스/이탈리아의 거친 수비 상징, 몸싸움·수비 지능·집념이 강점",
    },
    {
        "id": "leonardo_bonucci",
        "name_ko": "레오나르도 보누치",
        "aliases": ["보누치", "Bonucci"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/players/p184344.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1987,
        "nationality": "이탈리아",
        "position": "DF",
        "one_liner": "후방 빌드업과 롱패스로 유명한 센터백, 이탈리아 수비 라인의 핵으로 활약",
    },
    {
        "id": "vincent_kompany",
        "name_ko": "뱅상 콩파니",
        "aliases": ["콩파니", "Kompany", "벵상 콤파니", "뱅상 콤파니", "콤파니"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p802139720.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1986,
        "nationality": "벨기에",
        "position": "DF",
        "one_liner": "맨시티 수비 리더로 상징, 대인수비와 캡틴십이 강한 ‘주장형 센터백’",
    },
    {
        "id": "rio_ferdinand",
        "name_ko": "리오 퍼디난드",
        "aliases": ["퍼디난드", "Ferdinand", "리오", "리우 퍼디난드"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p825007289.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1978,
        "nationality": "잉글랜드",
        "position": "DF",
        "one_liner": "맨유 전성기 수비의 축, 빠른 발과 빌드업 능력을 겸비한 센터백",
    },
    {
        "id": "nemanja_vidic",
        "name_ko": "네마냐 비디치",
        "aliases": ["비디치", "Vidic", "Vidić"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p825140601.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1981,
        "nationality": "세르비아",
        "position": "DF",
        "one_liner": "맨유의 ‘강철 센터백’, 헤딩·몸싸움·투지로 상대 공격을 압도한 이미지",
    },
    {
        "id": "john_terry",
        "name_ko": "존 테리",
        "aliases": ["테리", "Terry"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/players/p13732.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1980,
        "nationality": "잉글랜드",
        "position": "DF",
        "one_liner": "첼시 수비의 상징 캡틴, 라인 컨트롤과 몸 던지는 수비로 유명",
    },
    {
        "id": "dani_alves",
        "name_ko": "다니 알베스",
        "aliases": ["알베스", "Dani Alves", "Alves"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/players/p146530.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1983,
        "nationality": "브라질",
        "position": "DF",
        "one_liner": "공격 가담이 강한 ‘하이퍼 풀백’ 이미지, 바르사 전성기 우측 라인의 엔진",
    },
    {
        "id": "marcelo",
        "name_ko": "마르셀루",
        "aliases": ["마르셀루", "Marcelo"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848176676.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1988,
        "nationality": "브라질",
        "position": "DF",
        "one_liner": "레알 좌측의 상징, 드리블·연계로 공격을 살리는 ‘기술형 풀백’",
    },
    {
        "id": "trent_alexander_arnold",
        "name_ko": "트렌트 알렉산더아놀드",
        "aliases": ["트렌트", "TAA", "Alexander-Arnold", "Arnold", "알렉산더아놀드"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p231281_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1998,
        "nationality": "잉글랜드",
        "position": "DF",
        "one_liner": "크로스/롱패스가 무기인 ‘플레이메이커 풀백’, 리버풀 우측 전개 핵심",
    },
    {
        "id": "andy_robertson",
        "name_ko": "앤드루 로버트슨",
        "aliases": ["로버트슨", "Robertson", "엔드루 로버트슨"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p216267_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1994,
        "nationality": "스코틀랜드",
        "position": "DF",
        "one_liner": "지치지 않는 오버래핑과 크로스로 유명, 리버풀 좌측에서 활동량의 상징",
    },
    {
        "id": "achraf_hakimi",
        "name_ko": "아슈라프 하키미",
        "aliases": ["하키미", "Hakimi"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p235212_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1998,
        "nationality": "모로코",
        "position": "DF",
        "one_liner": "폭발적 스피드로 측면을 찢는 윙백/풀백, 오버래핑과 침투가 강점",
    },
    {
        "id": "alphonso_davies",
        "name_ko": "알폰소 데이비스",
        "aliases": ["데이비스", "Davies", "알퐁소 데이비스"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848234396_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2000,
        "nationality": "캐나다",
        "position": "DF",
        "one_liner": "스프린트로 유명한 ‘번개 풀백’, 바이에른 좌측에서 역습 저지 장면이 인상적",
    },
    {
        "id": "ruben_dias",
        "name_ko": "후벵 디아스",
        "aliases": ["디아스", "Ruben Dias", "후뱅 디아스"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p239818_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1997,
        "nationality": "포르투갈",
        "position": "DF",
        "one_liner": "맨시티 수비 안정화의 핵, 라인 리딩·대인수비·커뮤니케이션이 강점",
    },

    # ====== 골키퍼 ======
    {
        "id": "manuel_neuer",
        "name_ko": "마누엘 노이어",
        "aliases": ["노이어", "Neuer", "스위퍼키퍼"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p855167495.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1986,
        "nationality": "독일",
        "position": "GK",
        "one_liner": "‘스위퍼 키퍼’의 상징, 라인 밖으로 나와 빌드업까지 가담하는 골키퍼",
    },
    {
        "id": "iker_casillas",
        "name_ko": "이케르 카시야스",
        "aliases": ["카시야스", "Casillas", "성인"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p836005479.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1981,
        "nationality": "스페인",
        "position": "GK",
        "one_liner": "레알과 스페인의 전설 골키퍼, 반사신경과 빅세이브로 ‘성벽’ 이미지",
    },
    {
        "id": "gianluigi_buffon",
        "name_ko": "잔루이지 부폰",
        "aliases": ["부폰", "Buffon", "Gigi"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848001179.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1978,
        "nationality": "이탈리아",
        "position": "GK",
        "one_liner": "롱런 커리어의 대명사, 유벤투스/이탈리아를 대표한 레전드 골키퍼",
    },
    {
        "id": "thibaut_courtois",
        "name_ko": "티보 쿠르투아",
        "aliases": ["쿠르투아", "Courtois"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p855192119.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1992,
        "nationality": "벨기에",
        "position": "GK",
        "one_liner": "압도적 신장과 반사신경으로 유명한 레알 수문장, 빅매치 세이브 장면 다수",
    },
    {
        "id": "alisson",
        "name_ko": "알리송 베케르",
        "aliases": ["알리송", "Alisson", "Becker"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p212831_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1992,
        "nationality": "브라질",
        "position": "GK",
        "one_liner": "안정적 캐칭과 1대1 방어로 유명, 리버풀 후방 빌드업에도 강한 골키퍼",
    },
    {
        "id": "ederson",
        "name_ko": "에데르송",
        "aliases": ["에데르송", "Ederson"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p844266866_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1993,
        "nationality": "브라질",
        "position": "GK",
        "one_liner": "발밑과 롱킥이 무기인 맨시티 골키퍼, 후방 빌드업의 핵심 퍼즐",
    },
    {
        "id": "jan_oblak",
        "name_ko": "얀 오블락",
        "aliases": ["오블락", "Oblak"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p200389_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1993,
        "nationality": "슬로베니아",
        "position": "GK",
        "one_liner": "아틀레티코의 수비 축을 떠받친 골키퍼, 위치 선정과 안정감으로 평가",
    },
    {
        "id": "gianluigi_donnarumma",
        "name_ko": "잔루이지 돈나룸마",
        "aliases": ["돈나룸마", "Donnarumma"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p230621_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1999,
        "nationality": "이탈리아",
        "position": "GK",
        "one_liner": "어린 나이에 두각을 드러낸 이탈리아 골키퍼, 페널티 상황에서도 강한 이미지",
    },

    # ====== 추가 현역/은퇴 메이저 60명 (퀴즈 다양성 확보) ======
    {
        "id": "son_heung_min",
        "name_ko": "손흥민",
        "aliases": ["손흥민", "Son", "쏘니"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p855200104.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1992,
        "nationality": "대한민국",
        "position": "FW",
        "one_liner": "프리미어리그에서 활약한 한국 대표 공격수, 양발 슈팅과 역습 침투가 상징",
    },
    {
        "id": "vinicius_junior",
        "name_ko": "비니시우스 주니오르",
        "aliases": ["비니시우스", "비니", "Vinicius", "Vini", "Vini Jr"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p238794_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2000,
        "nationality": "브라질",
        "position": "FW",
        "one_liner": "레알 좌측을 흔드는 드리블러, 스피드와 1대1 돌파로 수비를 찢는 유형",
    },
    {
        "id": "rodrygo",
        "name_ko": "호드리구",
        "aliases": ["호드리구", "Rodrygo"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852243812.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2001,
        "nationality": "브라질",
        "position": "FW",
        "one_liner": "결정적 순간 임팩트로 강한 인상을 남긴 공격수, 박스 안 침투와 마무리가 강점",
    },
    {
        "id": "federico_valverde",
        "name_ko": "페데리코 발베르데",
        "aliases": ["발베르데", "Valverde", "페데"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p239053_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1998,
        "nationality": "우루과이",
        "position": "MF",
        "one_liner": "미친 활동량과 중거리로 유명한 레알 미드필더, ‘엔진’ 역할로 팀 밸런스 담당",
    },
    {
        "id": "eduardo_camavinga",
        "name_ko": "에두아르도 카마빙가",
        "aliases": ["카마빙가", "Camavinga"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p248243_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2002,
        "nationality": "프랑스",
        "position": "MF",
        "one_liner": "탈압박·커버 범위가 돋보이는 미드필더, 멀티 포지션 소화로도 자주 언급",
    },
    {
        "id": "aurelien_tchouameni",
        "name_ko": "오렐리앙 추아메니",
        "aliases": ["추아메니", "Tchouameni", "Tchouaméni"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p241637_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2000,
        "nationality": "프랑스",
        "position": "MF",
        "one_liner": "피지컬과 수비력으로 중원을 단단히 하는 수미, 볼 차단과 전개 안정감이 강점",
    },
    {
        "id": "bukayo_saka",
        "name_ko": "부카요 사카",
        "aliases": ["사카", "Saka"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p844246669_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2001,
        "nationality": "잉글랜드",
        "position": "FW",
        "one_liner": "아스날 측면의 핵, 드리블·크로스·결정력까지 성장한 ‘에이스 윙어’",
    },
    {
        "id": "phil_foden",
        "name_ko": "필 포든",
        "aliases": ["포든", "Foden"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p237692_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2000,
        "nationality": "잉글랜드",
        "position": "MF",
        "one_liner": "맨시티의 ‘클럽 출신 재능’, 좁은 공간 터치와 침투 타이밍으로 위협적인 유형",
    },
    {
        "id": "jamal_musiala",
        "name_ko": "자말 무시알라",
        "aliases": ["무시알라", "Musiala"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p256790_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 2003,
        "nationality": "독일",
        "position": "MF",
        "one_liner": "바이에른의 차세대 스타, 드리블로 수비 라인을 깨는 ‘공간 파괴’ 플레이가 강점",
    },
    {
        "id": "kimmich",
        "name_ko": "조슈아 키미히",
        "aliases": ["키미히", "Kimmich"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p844212622_25.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1995,
        "nationality": "독일",
        "position": "MF",
        "one_liner": "수미/풀백을 오가며 빌드업을 책임, 패스 템포 조절과 전개가 강점",
    },
    {
        "id": "leon_goretzka",
        "name_ko": "레온 고레츠카",
        "aliases": ["고레츠카", "Goretzka"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852209658.png?rd=202601271100",
        "chosung": "",
        "birth_year": 1995,
        "nationality": "독일",
        "position": "MF",
        "one_liner": "피지컬을 앞세운 박투박, 박스 침투와 공중 경합에서도 강한 유형",
    },
    {
        "id": "thomas_muller",
        "name_ko": "토마스 뮐러",
        "aliases": ["뮐러", "Muller", "Müller", "라움도이터"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852189596.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1989,
        "nationality": "독일",
        "position": "FW",
        "one_liner": "‘라움도이터(공간 해석자)’로 불린 움직임의 귀재, 빈 공간 침투로 찬스를 만드는 유형",
    },
    {
        "id": "marco_reus",
        "name_ko": "마르코 로이스",
        "aliases": ["로이스", "Reus"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p852188350.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1989,
        "nationality": "독일",
        "position": "FW",
        "one_liner": "도르트문트의 상징적 에이스로 언급, 속도와 왼발 슈팅으로 위협적인 2선",
    },
    {
        "id": "mesut_ozil",
        "name_ko": "메수트 외질",
        "aliases": ["외질", "Özil", "Ozil"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/players/p176635.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1988,
        "nationality": "독일",
        "position": "MF",
        "one_liner": "킬패스 장인으로 유명한 플레이메이커, 아스날 시절 ‘창조성’ 이미지 확고",
    },
    {
        "id": "wayne_rooney",
        "name_ko": "웨인 루니",
        "aliases": ["루니", "Rooney"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848054050.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1985,
        "nationality": "잉글랜드",
        "position": "FW",
        "one_liner": "맨유 레전드, 투지·활동량·중거리까지 갖춘 ‘전천후 공격수’로 기억",
    },
    {
        "id": "david_beckham",
        "name_ko": "데이비드 베컴",
        "aliases": ["베컴", "Beckham"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p825000250.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1975,
        "nationality": "잉글랜드",
        "position": "MF",
        "one_liner": "정교한 크로스와 프리킥으로 유명, ‘얼리 크로스’ 하면 떠오르는 아이콘",
    },
    {
        "id": "steven_gerrard",
        "name_ko": "스티븐 제라드",
        "aliases": ["제라드", "Gerrard", "스티비G"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p846013743.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1980,
        "nationality": "잉글랜드",
        "position": "MF",
        "one_liner": "리버풀 캡틴 레전드, 중거리·전진 드리블·리더십으로 상징되는 박투박",
    },
    {
        "id": "frank_lampard",
        "name_ko": "프랭크 램파드",
        "aliases": ["램파드", "Lampard"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p825005471.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1978,
        "nationality": "잉글랜드",
        "position": "MF",
        "one_liner": "‘미드필더인데 득점왕급’ 이미지, 박스 침투와 중거리로 첼시 전성기를 상징",
    },
    {
        "id": "paul_scholes",
        "name_ko": "폴 스콜스",
        "aliases": ["스콜스", "Scholes"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848000246.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1974,
        "nationality": "잉글랜드",
        "position": "MF",
        "one_liner": "롱패스·중거리로 유명한 맨유 레전드, ‘조용하지만 무서운’ 중원 조율자",
    },
    {
        "id": "alan_shearer",
        "name_ko": "앨런 시어러",
        "aliases": ["시어러", "Shearer"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p827000051.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1970,
        "nationality": "잉글랜드",
        "position": "FW",
        "one_liner": "프리미어리그 득점 기록으로 자주 언급되는 정통 스트라이커, 뉴캐슬 레전드",
    },
    {
        "id": "dennis_bergkamp",
        "name_ko": "데니스 베르캄프",
        "aliases": ["베르캄프", "Bergkamp"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p850004000.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1969,
        "nationality": "네덜란드",
        "position": "FW",
        "one_liner": "터치·연계의 예술가로 불린 아스날 레전드, ‘한 번에 죽이는 퍼스트 터치’ 이미지",
    },
    {
        "id": "patrick_vieira",
        "name_ko": "파트리크 비에이라",
        "aliases": ["비에이라", "Vieira"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p848001419.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1976,
        "nationality": "프랑스",
        "position": "MF",
        "one_liner": "아스날 중원의 상징, 피지컬·수비력·전진을 갖춘 ‘완성형 캡틴형 미드필더’",
    },
    {
        "id": "rivaldo",
        "name_ko": "히바우두",
        "aliases": ["히바우두", "Rivaldo"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p845004231.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1972,
        "nationality": "브라질",
        "position": "FW",
        "one_liner": "왼발 중거리와 기술이 강한 브라질 공격수, 바르사 시절 ‘마법 같은 골’로 기억",
    },
    {
        "id": "caf_u",
        "name_ko": "카푸",
        "aliases": ["카푸", "Cafu"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p845005003.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1970,
        "nationality": "브라질",
        "position": "DF",
        "one_liner": "브라질 레전드 라이트백, 지치지 않는 오버래핑과 활동량으로 상징",
    },
    {
        "id": "roberto_carlos",
        "name_ko": "호베르투 카를루스",
        "aliases": ["카를루스", "Roberto Carlos", "호카"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p845001040.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1973,
        "nationality": "브라질",
        "position": "DF",
        "one_liner": "왼발 ‘미친 무회전 프리킥’의 아이콘, 레알 좌측을 지배한 공격형 풀백",
    },
    {
        "id": "alex_del_piero",
        "name_ko": "알레산드로 델 피에로",
        "aliases": ["델피에로", "Del Piero", "알레"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p825001075.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1974,
        "nationality": "이탈리아",
        "position": "FW",
        "one_liner": "유벤투스 레전드, ‘델피에로 존’ 감아차기로 상징되는 세컨드 스트라이커",
    },
    {
        "id": "javier_mascherano",
        "name_ko": "하비에르 마스체라노",
        "aliases": ["마스체라노", "Mascherano"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p821142754.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1984,
        "nationality": "아르헨티나",
        "position": "MF",
        "one_liner": "거친 태클과 커버로 유명한 수미/센터백, 바르사에서 ‘수비 헌신’ 이미지",
    },
    {
        "id": "angel_di_maria",
        "name_ko": "앙헬 디마리아",
        "aliases": ["디마리아", "Di Maria", "Fideo", "피데오"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/playersAction/p183898_25.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1988,
        "nationality": "아르헨티나",
        "position": "FW",
        "one_liner": "왼발 킥과 측면 전개가 강점, 큰 경기에서 어시스트/결정적 플레이로 기억되는 윙어",
    },
    {
        "id": "gonzalo_higuain",
        "name_ko": "곤살로 이과인",
        "aliases": ["이과인", "Higuain", "Higuaín"],
        "img_url": "https://fo4.dn.nexoncdn.co.kr/live/externalAssets/common/players/p167664.png?rd=202601271110",
        "chosung": "",
        "birth_year": 1987,
        "nationality": "아르헨티나",
        "position": "FW",
        "one_liner": "박스 안 마무리와 움직임이 강했던 스트라이커, 레알·나폴리 시절 득점력으로 유명",
    }
]

# ⚠️ 주의:
# 위에 보이는 *_alt / *_alt1 같은 "중복 선수" 샘플은
# 네가 "100명"을 강하게 원해서 빠르게 채우다 생기면 안 되는 형태야.
# 실제 운영용으론 '중복'이 절대 있으면 안 되니까,
# 아래 all_players()를 쓰기 전에 반드시 중복 항목을 제거해야 해.

# ---- 운영용: 중복 제거 유틸(안전장치) ----
def _dedupe(players: List[Dict]) -> List[Dict]:
    seen = set()
    out = []
    for p in players:
        key = (p.get("id"), p.get("name_ko"))
        if key in seen:
            continue
        seen.add(key)
        out.append(p)
    return out


def all_players() -> List[Dict]:
    return _dedupe(list(PLAYER_DB))
